# Generated by Django 6.0.2 on 2026-02-10 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, help_text='Gerado automaticamente ao salvar.', max_length=30, null=True, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(blank=True, help_text='Somente números (11 dígitos).', max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('data_inativacao', models.DateField(blank=True, null=True, verbose_name='Data de inativação')),
                ('cep', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=120, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
