# Generated by Django 6.0.2 on 2026-02-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistido',
            name='area_risco',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='complemento',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='assistido',
            name='data_inicio_apoio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistido',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistido',
            name='diabetes',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='doenca_permanente',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='escolaridade',
            field=models.CharField(choices=[('FUNDAMENTAL', 'Fundamental'), ('MEDIO', 'Médio'), ('SUPERIOR', 'Superior'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=30),
        ),
        migrations.AddField(
            model_name='assistido',
            name='faixa_renda',
            field=models.CharField(choices=[('ATE_1_SM', 'Até 1 salário mínimo'), ('DE_1_A_2_SM', 'De 1 a 2 salários mínimos'), ('ACIMA_2_SM', 'Acima de 2 salários mínimos'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='material_moradia',
            field=models.CharField(choices=[('ALVENARIA', 'Alvenaria'), ('MADEIRA', 'Madeira'), ('MISTA', 'Mista'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='medic_uso_continuo',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='motivo_inativacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assistido',
            name='pressao_alta',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='responsavel_renda',
            field=models.CharField(choices=[('ASSISTIDO', 'Assistido'), ('CONJUGE', 'Cônjuge'), ('OUTRO', 'Outro'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='sabe_ler_escrever',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='sit_trabalho',
            field=models.CharField(choices=[('EMPREGADO', 'Empregado'), ('DESEMPREGADO', 'Desempregado'), ('AUTONOMO', 'Autônomo'), ('APOSENTADO', 'Aposentado'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='assistido',
            name='tipo_moradia',
            field=models.CharField(choices=[('PROPRIA', 'Própria'), ('ALUGADA', 'Alugada'), ('CEDIDA', 'Cedida'), ('NAO_INFORMADO', 'Não informado')], default='NAO_INFORMADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='bairro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='cidade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='data_inativacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='logradouro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
