# Generated by Django 6.0.2 on 2026-02-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistidos', '0002_assistido_area_risco_assistido_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistido',
            name='data_inicio_apoio',
            field=models.DateField(blank=True, null=True, verbose_name='Ingresso no Programa'),
        ),
    ]
