# Generated by Django 6.0.2 on 2026-02-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistidos', '0003_alter_assistido_data_inicio_apoio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistido',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='assistido',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
