# Generated by Django 6.0.2 on 2026-02-10 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('categoria', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('VESTUARIO', 'Vestuário'), ('OUTROS', 'Outros')], max_length=20)),
                ('periodicidade', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('OCASIONAL', 'Ocasional')], max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Permite desativar um benefício sem apagá-lo.')),
            ],
            options={
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioAssistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Permite encerrar a atribuição sem apagar histórico.')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('assistido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficios_atribuidos', to='assistidos.assistido')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistidos_atribuidos', to='beneficios.beneficio')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LoteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_entrega', to='beneficios.beneficio')),
            ],
            options={
                'verbose_name': 'Lote de Entrega',
                'verbose_name_plural': 'Lotes de Entrega',
                'ordering': ('-data_entrega', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ItemEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregue', models.BooleanField(default=False)),
                ('atribuicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='beneficios.beneficioassistido')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='beneficios.loteentrega')),
            ],
            options={
                'verbose_name': 'Item de Entrega',
                'verbose_name_plural': 'Itens de Entrega',
                'ordering': ('atribuicao__assistido__nome',),
            },
        ),
        migrations.AddConstraint(
            model_name='beneficioassistido',
            constraint=models.UniqueConstraint(fields=('assistido', 'beneficio'), name='uniq_assistido_beneficio'),
        ),
        migrations.AlterUniqueTogether(
            name='loteentrega',
            unique_together={('beneficio', 'data_entrega')},
        ),
        migrations.AlterUniqueTogether(
            name='itementrega',
            unique_together={('lote', 'atribuicao')},
        ),
    ]
