# Generated by Django 6.0.2 on 2026-02-13 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficioassistido',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='beneficioassistido',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
