# Generated by Django 6.0.2 on 2026-02-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistidos', '0004_alter_assistido_cep_alter_assistido_cpf_and_more'),
        ('beneficios', '0002_beneficioassistido_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='beneficioassistido',
            name='uniq_assistido_beneficio',
        ),
        migrations.AddConstraint(
            model_name='beneficioassistido',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('assistido', 'beneficio'), name='uniq_assistido_beneficio_ativo'),
        ),
    ]
